Stat svc
sabolenok/java-explore-with-me pull request #2
Opened 2023-01-28 13:00 UTC by sabolenok

2023-01-29 13:01 UTC, sergeymamonov requested changes

2023-01-31 19:50 UTC, sergeymamonov approved these changes
В модуле stats есть папка src - это лишняя папка. Ее нужно удалить со всем содержимым. Должна быть иерархия помников. То есть у корневого помника только два модуля ewm-service и stats. Помники stats-server и другие должны иметь родителя stats.

Из улучшений, можно добавить валидацию входных данных. Ведь может же придти время endDate < startDate. А если какой-нибудь параметр придет со значением null?

2023-01-31 19:50 UTC, sergeymamonov commented on stats/stats-client/pom.xml
> +        <artifactId>explore-with-me</artifactId>
У этого помника родитель stats.

2023-01-31 19:50 UTC, sergeymamonov commented on stats/stats-server/src/main/java/ru/practicum/explore_with_me/stats/StatsService.java
> +    public List<StatWithCount> getStats(String start, String end, List<String> uris, boolean unique) {
Рекомендую выделить участки кода из этого метода в отдельные методы, чтобы код стал более читаемым. Особенно цикл с ифом, чтобы код цикла был короче и более читаем.

2023-01-31 19:50 UTC, sergeymamonov commented on stats/stats-client/src/main/java/ru/practicum/explore_with_me/client/StatsClient.java
> +    public List<StatWithCount> getStats(String start, String end, List<String> uris, Boolean unique)
Сейчас в метод передаются 4 параметра. Например, завтра придет задача добавить еще один параметр, потом еще один. И так далее. Поэтому делают отдельный класс ...Request, куда собирают все параметры. И при добавлении или удалении параметра, сигнатура метода не меняется.

2023-02-01 13:30 UTC, sabolenok commented
Замечания исправлены в новой ветке main_svc

2023-02-15 05:07 UTC, merged