Основной сервис
sabolenok/java-explore-with-me pull request #3
Opened 2023-02-07 13:05 UTC by sabolenok

2023-02-08 20:19 UTC, sergeymamonov requested changes

2023-02-08 20:19 UTC, sergeymamonov commented on ewm-service/src/main/java/ru/practicum/explore_with_me/event_request/RequestService.java
> +    public EventRequest create(Integer userId, Integer eventId) {
Много сток кода в методе

2023-02-08 20:19 UTC, sergeymamonov commented on ewm-service/src/main/java/ru/practicum/explore_with_me/event_request/RequestService.java
> +        if (foundEvent.isPresent()) {
Код практически всего метода сдвинут вправо из-за ифа. Елсе в самом низу. Это очень неудобно. Можно проще

if (!foundEvent.isPresent()) {
throw new NotFoundException(String.format("Event with id=%d was not found", eventId),
                    "The required object was not found.");
}

//Дальше код из ифа. И он не будет сдвинут вправо, как сейчас

2023-02-08 20:19 UTC, sergeymamonov commented on ewm-service/src/main/java/ru/practicum/explore_with_me/event_request/RequestService.java
> +                if (request.getRequesterId() != userId) {
Я бы такие ифы выделял бы в validateRequest() как-то так.

2023-02-08 20:19 UTC, sergeymamonov commented on ewm-service/src/main/java/ru/practicum/explore_with_me/user/dto/UserDto.java
> +    @NotBlank(message = "Логин не может быть пустым")
Где-то логирование на английском, а здесь на русском. Лучше использовать один язык.

2023-02-09 11:33 UTC, sabolenok commented on ewm-service/src/main/resources/schema.sql
> +                                     annotation VARCHAR NOT NULL,
Добавлено ограничение

2023-02-09 11:34 UTC, sabolenok commented on ewm-service/src/main/java/ru/practicum/explore_with_me/controllers/CategoryPublicController.java
> +    public List<CategoryDto> getAll(@RequestParam(required = false, defaultValue = "0") Integer from,
Дoбавила @Positive, @PostitveOrZero

2023-02-09 11:35 UTC, sabolenok commented on ewm-service/src/main/java/ru/practicum/explore_with_me/event/EventService.java
> +        wrappedRequest.addParameter("start", LocalDateTime.now().minusDays(180).format(formatter));
Изменено на private final переменную

2023-02-09 11:35 UTC, sabolenok commented on ewm-service/src/main/java/ru/practicum/explore_with_me/event/EventService.java
> +    static Specification<Event> hasInitiatorIn(Integer[] userIds) {
Изменены на private

2023-02-09 11:35 UTC, sabolenok commented on ewm-service/src/main/java/ru/practicum/explore_with_me/event/EventService.java
> +    private void fillInformationInUpdatedEvent(Event event, Event eventPrevious, String stateAction, boolean isAdmin) {
done

2023-02-09 11:35 UTC, sabolenok commented on ewm-service/src/main/java/ru/practicum/explore_with_me/event/EventService.java
> +                if (currentState.equals(EventState.PENDING)) {
done

2023-02-09 11:35 UTC, sabolenok commented on ewm-service/src/main/java/ru/practicum/explore_with_me/event_request/RequestService.java
> +    public EventRequest create(Integer userId, Integer eventId) {
done

2023-02-09 11:36 UTC, sabolenok commented on ewm-service/src/main/java/ru/practicum/explore_with_me/event_request/RequestService.java
> +        if (foundEvent.isPresent()) {
done

2023-02-09 11:36 UTC, sabolenok commented on ewm-service/src/main/java/ru/practicum/explore_with_me/event_request/RequestService.java
> +            if (foundEvent.isPresent()) {
done

2023-02-09 11:36 UTC, sabolenok commented on ewm-service/src/main/java/ru/practicum/explore_with_me/event_request/RequestService.java
> +                if (request.getRequesterId() != userId) {
done

2023-02-09 11:36 UTC, sabolenok commented on ewm-service/src/main/java/ru/practicum/explore_with_me/user/dto/UserDto.java
> +    @NotBlank(message = "Логин не может быть пустым")
Исправлено на английский

2023-02-11 12:08 UTC, sergeymamonov approved these changes

2023-02-11 12:08 UTC, sergeymamonov commented on ewm-service/src/main/java/ru/practicum/explore_with_me/event/EventService.java
> +    private final DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss");
Нужно добавить модификатор static, чтобы константы создавалась один раз. И использовать CONSTANT_CASE для написания имени. На строке 60 аналогично.

2023-02-13 10:38 UTC, sabolenok commented on ewm-service/src/main/java/ru/practicum/explore_with_me/event/EventService.java
> +    private final DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss");
Исправлено

2023-02-13 10:38 UTC, sabolenok commented on ewm-service/src/main/resources/schema.sql
> +                                     annotation VARCHAR NOT NULL,
Исправлено

2023-02-15 05:04 UTC, merged