Feature comments
sabolenok/java-explore-with-me pull request #4
Opened 2023-02-13 13:35 UTC by sabolenok

2023-02-14 15:06 UTC, sergeymamonov requested changes
Сейчас в пулл реквесте все коммиты, то есть все изменения, которые сделаны за все время работы над дипломом. Так не делают. Есть основная ветка. И есть ветки, в которых мы добавляем новый функционал (или что-то правим). Как только мы сделали работу над задачей, код проходит ревью, и мы вмерживаем этот код в основную ветку. Поэтому в следующем пулл реквесте мы видим только новые изменения над кодом. То есть сейчас увидеть новую фичу в вашем пулл реквесте очень сложно. Для этого вмержите предыдущие пулл реквесты.

2023-02-14 15:06 UTC, sergeymamonov commented on ewm-service/src/main/java/ru/practicum/explore_with_me/exception/DoubleEventRequestException.java
> +public class DoubleEventRequestException extends ValidationException {
А где вызывается это исключение?

2023-02-15 05:15 UTC, sabolenok commented on ewm-service/src/main/java/ru/practicum/explore_with_me/exception/DoubleEventRequestException.java
> +public class DoubleEventRequestException extends ValidationException {
Планировала вызывать при создании EventRequest и, видимо, упустила. Исправлено

2023-02-15 18:13 UTC, sergeymamonov approved these changes

2023-02-16 04:55 UTC, merged